// This file was auto-generated by the veyron vdl tool.
var vdl = require('../../../../../.././vdl');






module.exports = {};



// Types:
var _type1 = new vdl.Type();
var _type2 = new vdl.Type();
var _typeServerRPCReply = new vdl.Type();
var _typeerror = new vdl.Type();
_type1.kind = vdl.Kind.LIST;
_type1.name = "";
_type1.elem = vdl.Types.ANY;
_type2.kind = vdl.Kind.STRUCT;
_type2.name = "";
_type2.fields = [{name: "ID", type: vdl.Types.STRING}, {name: "Action", type: vdl.Types.UINT32}];
_typeServerRPCReply.kind = vdl.Kind.STRUCT;
_typeServerRPCReply.name = "v.io/wspr/veyron/services/wsprd/lib.ServerRPCReply";
_typeServerRPCReply.fields = [{name: "Results", type: _type1}, {name: "Err", type: vdl.Types.ERROR}];
_typeerror.kind = vdl.Kind.STRUCT;
_typeerror.name = "error";
_typeerror.fields = [{name: "IDAction", type: _type2}, {name: "Msg", type: vdl.Types.STRING}, {name: "ParamList", type: _type1}];
_type1.freeze();
_type2.freeze();
_typeServerRPCReply.freeze();
_typeerror.freeze();
module.exports.ServerRPCReply = (vdl.Registry.lookupOrCreateConstructor(_typeServerRPCReply));
module.exports.error = (vdl.Registry.lookupOrCreateConstructor(_typeerror));




// Consts:



// Errors:



// Services:

   
 


