// This file was auto-generated by the veyron vdl tool.
var vom = require('../../../../../.././vom/vom');





module.exports = {};



// Types:
var _type1 = new vom.Type();
var _type2 = new vom.Type();
var _type3 = new vom.Type();
var _typeServerRPCReply = new vom.Type();
var _typeerror = new vom.Type();
_type1.kind = vom.Kind.LIST;
_type1.name = "";
_type1.elem = vom.Types.ANY;
_type2.kind = vom.Kind.OPTIONAL;
_type2.name = "";
_type2.elem = _typeerror;
_type3.kind = vom.Kind.STRUCT;
_type3.name = "";
_type3.fields = [{name: "ID", type: vom.Types.STRING}, {name: "Action", type: vom.Types.UINT32}];
_typeServerRPCReply.kind = vom.Kind.STRUCT;
_typeServerRPCReply.name = "v.io/wspr/veyron/services/wsprd/lib.ServerRPCReply";
_typeServerRPCReply.fields = [{name: "Results", type: _type1}, {name: "Err", type: _type2}];
_typeerror.kind = vom.Kind.STRUCT;
_typeerror.name = "error";
_typeerror.fields = [{name: "IDAction", type: _type3}, {name: "Msg", type: vom.Types.STRING}, {name: "ParamList", type: _type1}];
module.exports.ServerRPCReply = (vom.Registry.lookupOrCreateConstructor(_typeServerRPCReply));
module.exports.error = (vom.Registry.lookupOrCreateConstructor(_typeerror));




// Consts:



// Errors:



function NotImplementedMethod(name) {
  throw new Error('Method ' + name + ' not implemented');
}


// Services:

   
 


