// This file was auto-generated by the veyron vdl tool.
var vom = require('vom');
// TODO(bjornick): Remove unused imports.
var Types = vom.Types;
var Type = vom.Type;
var Kind = vom.Kind;
var Complex = vom.Complex;
var Builtins = vom.Builtins;
var Registry = vom.Registry;






var types = {};
var _type1 = new Type();
var _type10 = new Type();
var _type11 = new Type();
var _type12 = new Type();
var _type13 = new Type();
var _type14 = new Type();
var _type15 = new Type();
var _type16 = new Type();
var _type17 = new Type();
var _type18 = new Type();
var _type19 = new Type();
var _type2 = new Type();
var _type20 = new Type();
var _type21 = new Type();
var _type22 = new Type();
var _type23 = new Type();
var _type24 = new Type();
var _type25 = new Type();
var _type26 = new Type();
var _type27 = new Type();
var _type28 = new Type();
var _type29 = new Type();
var _type3 = new Type();
var _type30 = new Type();
var _type4 = new Type();
var _type5 = new Type();
var _type6 = new Type();
var _type7 = new Type();
var _type8 = new Type();
var _type9 = new Type();
var _typeArgs = new Type();
var _typeCompComp = new Type();
var _typeComposites = new Type();
var _typeKeyScalars = new Type();
var _typeNamedArray = new Type();
var _typeNamedBool = new Type();
var _typeNamedByte = new Type();
var _typeNamedComplex128 = new Type();
var _typeNamedComplex64 = new Type();
var _typeNamedFloat32 = new Type();
var _typeNamedFloat64 = new Type();
var _typeNamedInt16 = new Type();
var _typeNamedInt32 = new Type();
var _typeNamedInt64 = new Type();
var _typeNamedList = new Type();
var _typeNamedMap = new Type();
var _typeNamedSet = new Type();
var _typeNamedString = new Type();
var _typeNamedStruct = new Type();
var _typeNamedUint16 = new Type();
var _typeNamedUint32 = new Type();
var _typeNamedUint64 = new Type();
var _typeNestedArgs = new Type();
var _typeScalars = new Type();
var _typeerror = new Type();
_type1.kind = Kind.BOOL;
_type10.kind = Kind.INT64;
_type11.kind = Kind.FLOAT64;
_type12.kind = Kind.COMPLEX64;
_type13.kind = Kind.COMPLEX128;
_type14.kind = Kind.NILABLE;
_type14.elem = _typeerror;
_type15.kind = Kind.STRUCT;
_type15.fields = [{name: "ID", type: _type3}, {name: "Action", type: _type2}];
_type16.kind = Kind.LIST;
_type16.elem = _type17;
_type17.kind = Kind.ANY;
_type18.kind = Kind.TYPEOBJECT;
_type19.kind = Kind.ARRAY;
_type19.len = 2;
_type19.elem = _typeScalars;
_type2.kind = Kind.UINT32;
_type20.kind = Kind.LIST;
_type20.elem = _typeScalars;
_type21.kind = Kind.SET;
_type21.key = _typeKeyScalars;
_type22.kind = Kind.MAP;
_type22.elem = _typeScalars;
_type22.key = _type3;
_type23.kind = Kind.MAP;
_type23.elem = _type24;
_type23.key = _typeKeyScalars;
_type24.kind = Kind.LIST;
_type24.elem = _type25;
_type25.kind = Kind.MAP;
_type25.elem = _type13;
_type25.key = _type3;
_type26.kind = Kind.ARRAY;
_type26.len = 2;
_type26.elem = _typeComposites;
_type27.kind = Kind.LIST;
_type27.elem = _typeComposites;
_type28.kind = Kind.MAP;
_type28.elem = _typeComposites;
_type28.key = _type3;
_type29.kind = Kind.MAP;
_type29.elem = _type30;
_type29.key = _typeKeyScalars;
_type3.kind = Kind.STRING;
_type30.kind = Kind.LIST;
_type30.elem = _type28;
_type4.kind = Kind.FLOAT32;
_type5.kind = Kind.INT32;
_type6.kind = Kind.BYTE;
_type7.kind = Kind.UINT16;
_type8.kind = Kind.UINT64;
_type9.kind = Kind.INT16;
_typeArgs.kind = Kind.STRUCT;
_typeArgs.name = "veyron.io/veyron/veyron2/vdl/testdata/base.Args";
_typeArgs.fields = [{name: "A", type: _type5}, {name: "B", type: _type5}];
_typeCompComp.kind = Kind.STRUCT;
_typeCompComp.name = "veyron.io/veyron/veyron2/vdl/testdata/base.CompComp";
_typeCompComp.fields = [{name: "A0", type: _typeComposites}, {name: "A1", type: _type26}, {name: "A2", type: _type27}, {name: "A3", type: _type28}, {name: "A4", type: _type29}];
_typeComposites.kind = Kind.STRUCT;
_typeComposites.name = "veyron.io/veyron/veyron2/vdl/testdata/base.Composites";
_typeComposites.fields = [{name: "A0", type: _typeScalars}, {name: "A1", type: _type19}, {name: "A2", type: _type20}, {name: "A3", type: _type21}, {name: "A4", type: _type22}, {name: "A5", type: _type23}];
_typeKeyScalars.kind = Kind.STRUCT;
_typeKeyScalars.name = "veyron.io/veyron/veyron2/vdl/testdata/base.KeyScalars";
_typeKeyScalars.fields = [{name: "A0", type: _type1}, {name: "A1", type: _type6}, {name: "A2", type: _type7}, {name: "A3", type: _type2}, {name: "A4", type: _type8}, {name: "A5", type: _type9}, {name: "A6", type: _type5}, {name: "A7", type: _type10}, {name: "A8", type: _type4}, {name: "A9", type: _type11}, {name: "A10", type: _type12}, {name: "A11", type: _type13}, {name: "A12", type: _type3}, {name: "B0", type: _typeNamedBool}, {name: "B1", type: _typeNamedByte}, {name: "B2", type: _typeNamedUint16}, {name: "B3", type: _typeNamedUint32}, {name: "B4", type: _typeNamedUint64}, {name: "B5", type: _typeNamedInt16}, {name: "B6", type: _typeNamedInt32}, {name: "B7", type: _typeNamedInt64}, {name: "B8", type: _typeNamedFloat32}, {name: "B9", type: _typeNamedFloat64}, {name: "B10", type: _typeNamedComplex64}, {name: "B11", type: _typeNamedComplex128}, {name: "B12", type: _typeNamedString}];
_typeNamedArray.kind = Kind.ARRAY;
_typeNamedArray.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedArray";
_typeNamedArray.len = 2;
_typeNamedArray.elem = _type1;
_typeNamedBool.kind = Kind.BOOL;
_typeNamedBool.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedBool";
_typeNamedByte.kind = Kind.BYTE;
_typeNamedByte.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedByte";
_typeNamedComplex128.kind = Kind.COMPLEX128;
_typeNamedComplex128.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedComplex128";
_typeNamedComplex64.kind = Kind.COMPLEX64;
_typeNamedComplex64.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedComplex64";
_typeNamedFloat32.kind = Kind.FLOAT32;
_typeNamedFloat32.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedFloat32";
_typeNamedFloat64.kind = Kind.FLOAT64;
_typeNamedFloat64.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedFloat64";
_typeNamedInt16.kind = Kind.INT16;
_typeNamedInt16.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedInt16";
_typeNamedInt32.kind = Kind.INT32;
_typeNamedInt32.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedInt32";
_typeNamedInt64.kind = Kind.INT64;
_typeNamedInt64.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedInt64";
_typeNamedList.kind = Kind.LIST;
_typeNamedList.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedList";
_typeNamedList.elem = _type2;
_typeNamedMap.kind = Kind.MAP;
_typeNamedMap.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedMap";
_typeNamedMap.elem = _type4;
_typeNamedMap.key = _type3;
_typeNamedSet.kind = Kind.SET;
_typeNamedSet.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedSet";
_typeNamedSet.key = _type3;
_typeNamedString.kind = Kind.STRING;
_typeNamedString.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedString";
_typeNamedStruct.kind = Kind.STRUCT;
_typeNamedStruct.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedStruct";
_typeNamedStruct.fields = [{name: "A", type: _type1}, {name: "B", type: _type3}, {name: "C", type: _type5}];
_typeNamedUint16.kind = Kind.UINT16;
_typeNamedUint16.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedUint16";
_typeNamedUint32.kind = Kind.UINT32;
_typeNamedUint32.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedUint32";
_typeNamedUint64.kind = Kind.UINT64;
_typeNamedUint64.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NamedUint64";
_typeNestedArgs.kind = Kind.STRUCT;
_typeNestedArgs.name = "veyron.io/veyron/veyron2/vdl/testdata/base.NestedArgs";
_typeNestedArgs.fields = [{name: "Args", type: _typeArgs}];
_typeScalars.kind = Kind.STRUCT;
_typeScalars.name = "veyron.io/veyron/veyron2/vdl/testdata/base.Scalars";
_typeScalars.fields = [{name: "A0", type: _type1}, {name: "A1", type: _type6}, {name: "A2", type: _type7}, {name: "A3", type: _type2}, {name: "A4", type: _type8}, {name: "A5", type: _type9}, {name: "A6", type: _type5}, {name: "A7", type: _type10}, {name: "A8", type: _type4}, {name: "A9", type: _type11}, {name: "A10", type: _type12}, {name: "A11", type: _type13}, {name: "A12", type: _type3}, {name: "A13", type: _type14}, {name: "A14", type: _type17}, {name: "A15", type: _type18}, {name: "B0", type: _typeNamedBool}, {name: "B1", type: _typeNamedByte}, {name: "B2", type: _typeNamedUint16}, {name: "B3", type: _typeNamedUint32}, {name: "B4", type: _typeNamedUint64}, {name: "B5", type: _typeNamedInt16}, {name: "B6", type: _typeNamedInt32}, {name: "B7", type: _typeNamedInt64}, {name: "B8", type: _typeNamedFloat32}, {name: "B9", type: _typeNamedFloat64}, {name: "B10", type: _typeNamedComplex64}, {name: "B11", type: _typeNamedComplex128}, {name: "B12", type: _typeNamedString}];
_typeerror.kind = Kind.STRUCT;
_typeerror.name = "error";
_typeerror.fields = [{name: "IDAction", type: _type15}, {name: "Msg", type: _type3}, {name: "ParamList", type: _type16}];
types.Args = Registry.lookupOrCreateConstructor(_typeArgs, "Args");
types.CompComp = Registry.lookupOrCreateConstructor(_typeCompComp, "CompComp");
types.Composites = Registry.lookupOrCreateConstructor(_typeComposites, "Composites");
types.KeyScalars = Registry.lookupOrCreateConstructor(_typeKeyScalars, "KeyScalars");
types.NamedArray = Registry.lookupOrCreateConstructor(_typeNamedArray, "NamedArray");
types.NamedBool = Registry.lookupOrCreateConstructor(_typeNamedBool, "NamedBool");
types.NamedByte = Registry.lookupOrCreateConstructor(_typeNamedByte, "NamedByte");
types.NamedComplex128 = Registry.lookupOrCreateConstructor(_typeNamedComplex128, "NamedComplex128");
types.NamedComplex64 = Registry.lookupOrCreateConstructor(_typeNamedComplex64, "NamedComplex64");
types.NamedFloat32 = Registry.lookupOrCreateConstructor(_typeNamedFloat32, "NamedFloat32");
types.NamedFloat64 = Registry.lookupOrCreateConstructor(_typeNamedFloat64, "NamedFloat64");
types.NamedInt16 = Registry.lookupOrCreateConstructor(_typeNamedInt16, "NamedInt16");
types.NamedInt32 = Registry.lookupOrCreateConstructor(_typeNamedInt32, "NamedInt32");
types.NamedInt64 = Registry.lookupOrCreateConstructor(_typeNamedInt64, "NamedInt64");
types.NamedList = Registry.lookupOrCreateConstructor(_typeNamedList, "NamedList");
types.NamedMap = Registry.lookupOrCreateConstructor(_typeNamedMap, "NamedMap");
types.NamedSet = Registry.lookupOrCreateConstructor(_typeNamedSet, "NamedSet");
types.NamedString = Registry.lookupOrCreateConstructor(_typeNamedString, "NamedString");
types.NamedStruct = Registry.lookupOrCreateConstructor(_typeNamedStruct, "NamedStruct");
types.NamedUint16 = Registry.lookupOrCreateConstructor(_typeNamedUint16, "NamedUint16");
types.NamedUint32 = Registry.lookupOrCreateConstructor(_typeNamedUint32, "NamedUint32");
types.NamedUint64 = Registry.lookupOrCreateConstructor(_typeNamedUint64, "NamedUint64");
types.NestedArgs = Registry.lookupOrCreateConstructor(_typeNestedArgs, "NestedArgs");
types.Scalars = Registry.lookupOrCreateConstructor(_typeScalars, "Scalars");
types.error = Registry.lookupOrCreateConstructor(_typeerror, "error");



var consts = { 
  Cbool: new (Registry.lookupOrCreateConstructor(_type1))(true),
  Cbyte: new (Registry.lookupOrCreateConstructor(_type6))(1),
  Cint32: new (Registry.lookupOrCreateConstructor(_type5))(2),
  Cint64: new (Registry.lookupOrCreateConstructor(_type10))(3),
  Cuint32: new (Registry.lookupOrCreateConstructor(_type2))(4),
  Cuint64: new (Registry.lookupOrCreateConstructor(_type8))(5),
  Cfloat32: new (Registry.lookupOrCreateConstructor(_type4))(6),
  Cfloat64: new (Registry.lookupOrCreateConstructor(_type11))(7),
  CNamedBool: new (Registry.lookupOrCreateConstructor(_typeNamedBool))(true),
  CNamedStruct: new (Registry.lookupOrCreateConstructor(_typeNamedStruct))({
  'a': true,
  'b': "test",
  'c': 0,
}),
  Ccomplex64: new (Registry.lookupOrCreateConstructor(_type12))(new Complex(8.000000, 9.000000)),
  Ccomplex128: new (Registry.lookupOrCreateConstructor(_type13))(new Complex(10.000000, 11.000000)),
  Cstring: new (Registry.lookupOrCreateConstructor(_type3))("foo"),
  True: new (Registry.lookupOrCreateConstructor(_type1))(true),
  Foo: new (Registry.lookupOrCreateConstructor(_type3))("foo"),
  Five: new (Registry.lookupOrCreateConstructor(_type5))(5),
  Six: new (Registry.lookupOrCreateConstructor(_type8))(6),
  SixSquared: new (Registry.lookupOrCreateConstructor(_type8))(36),
  FiveSquared: new (Registry.lookupOrCreateConstructor(_type5))(25),
};


function NotImplementedMethod(name) {
  throw new Error('Method ' + name + ' not implemented');
}


var services = {
package: 'veyron.io/veyron/veyron2/vdl/testdata/base',
  ServiceA: {
    MethodA1: {
    numInArgs: 0,
    numOutArgs: 0,
    inputStreaming: false,
    outputStreaming: false,
    tags: []
},
    MethodA2: {
    numInArgs: 2,
    numOutArgs: 1,
    inputStreaming: false,
    outputStreaming: false,
    tags: []
},
    MethodA3: {
    numInArgs: 1,
    numOutArgs: 1,
    inputStreaming: false,
    outputStreaming: true,
    tags: [new (Registry.lookupOrCreateConstructor(_type3))("tag"), new (Registry.lookupOrCreateConstructor(_type8))(6), ]
},
    MethodA4: {
    numInArgs: 1,
    numOutArgs: 0,
    inputStreaming: true,
    outputStreaming: true,
    tags: []
},

},
  ServiceB: {
    MethodB1: {
    numInArgs: 2,
    numOutArgs: 1,
    inputStreaming: false,
    outputStreaming: false,
    tags: []
},
    MethodA1: {
    numInArgs: 0,
    numOutArgs: 0,
    inputStreaming: false,
    outputStreaming: false,
    tags: []
},
    MethodA2: {
    numInArgs: 2,
    numOutArgs: 1,
    inputStreaming: false,
    outputStreaming: false,
    tags: []
},
    MethodA3: {
    numInArgs: 1,
    numOutArgs: 1,
    inputStreaming: false,
    outputStreaming: true,
    tags: [new (Registry.lookupOrCreateConstructor(_type3))("tag"), new (Registry.lookupOrCreateConstructor(_type8))(6), ]
},
    MethodA4: {
    numInArgs: 1,
    numOutArgs: 0,
    inputStreaming: true,
    outputStreaming: true,
    tags: []
},

},

};


var serviceDefs = {
  package: 'veyron.io/veyron/veyron2/vdl/testdata/base',

  
  ServiceA: ServiceA,
  
  ServiceB: ServiceB,
  

};



  
    
function ServiceA(){}
    
      
ServiceA.prototype.MethodA1 = NotImplementedMethod;
    
      
ServiceA.prototype.MethodA2 = NotImplementedMethod;
    
      
ServiceA.prototype.MethodA3 = NotImplementedMethod;
    
      
ServiceA.prototype.MethodA4 = NotImplementedMethod;
    
    
ServiceA.prototype.signature = function ServiceASignature() {
  return _ServiceASignature;
};
    
var _ServiceASignature = {
  name: 'ServiceA',
  pkgPath: 'veyron.io/veyron/veyron2/vdl/testdata/base',
  doc: "",
  embeds: [],
  methods: [
    
      
    {
    name: 'MethodA1',
    doc: "",
    inArgs: [],
    outArgs: [{
      name: '',
      doc: "",
      type: _type14
    },
    ],
    inStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    outStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    hasInStreamHACK: false,
    hasOutStreamHACK: false,
    tags: []
  },
    
      
    {
    name: 'MethodA2',
    doc: "",
    inArgs: [{
      name: 'a',
      doc: "",
      type: _type5
    },
    {
      name: 'b',
      doc: "",
      type: _type3
    },
    ],
    outArgs: [{
      name: 's',
      doc: "",
      type: _type3
    },
    {
      name: 'err',
      doc: "",
      type: _type14
    },
    ],
    inStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    outStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    hasInStreamHACK: false,
    hasOutStreamHACK: false,
    tags: []
  },
    
      
    {
    name: 'MethodA3',
    doc: "",
    inArgs: [{
      name: 'a',
      doc: "",
      type: _type5
    },
    ],
    outArgs: [{
      name: 's',
      doc: "",
      type: _type3
    },
    {
      name: 'err',
      doc: "",
      type: _type14
    },
    ],
    inStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    outStreamHACK: {
      name: '',
      doc: '',
      type: _typeScalars
    },
    hasInStreamHACK: false,
    hasOutStreamHACK: true,
    tags: [new (Registry.lookupOrCreateConstructor(_type3))("tag"), new (Registry.lookupOrCreateConstructor(_type8))(6), ]
  },
    
      
    {
    name: 'MethodA4',
    doc: "",
    inArgs: [{
      name: 'a',
      doc: "",
      type: _type5
    },
    ],
    outArgs: [{
      name: '',
      doc: "",
      type: _type14
    },
    ],
    inStreamHACK: {
      name: '',
      doc: '',
      type: _type5
    },
    outStreamHACK: {
      name: '',
      doc: '',
      type: _type3
    },
    hasInStreamHACK: true,
    hasOutStreamHACK: true,
    tags: []
  },
    
  ]
};
  
    
function ServiceB(){}
    
      
ServiceB.prototype.MethodB1 = NotImplementedMethod;
    
      
ServiceB.prototype.MethodA1 = NotImplementedMethod;
    
      
ServiceB.prototype.MethodA2 = NotImplementedMethod;
    
      
ServiceB.prototype.MethodA3 = NotImplementedMethod;
    
      
ServiceB.prototype.MethodA4 = NotImplementedMethod;
    
    
ServiceB.prototype.signature = function ServiceBSignature() {
  return _ServiceBSignature;
};
    
var _ServiceBSignature = {
  name: 'ServiceB',
  pkgPath: 'veyron.io/veyron/veyron2/vdl/testdata/base',
  doc: "",
  embeds: [{
      name: 'ServiceA',
      pkgPath: 'veyron.io/veyron/veyron2/vdl/testdata/base',
      doc: ""
    },
    ],
  methods: [
    
      
    {
    name: 'MethodB1',
    doc: "",
    inArgs: [{
      name: 'a',
      doc: "",
      type: _typeScalars
    },
    {
      name: 'b',
      doc: "",
      type: _typeComposites
    },
    ],
    outArgs: [{
      name: 'c',
      doc: "",
      type: _typeCompComp
    },
    {
      name: 'err',
      doc: "",
      type: _type14
    },
    ],
    inStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    outStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    hasInStreamHACK: false,
    hasOutStreamHACK: false,
    tags: []
  },
    
      
    {
    name: 'MethodA1',
    doc: "",
    inArgs: [],
    outArgs: [{
      name: '',
      doc: "",
      type: _type14
    },
    ],
    inStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    outStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    hasInStreamHACK: false,
    hasOutStreamHACK: false,
    tags: []
  },
    
      
    {
    name: 'MethodA2',
    doc: "",
    inArgs: [{
      name: 'a',
      doc: "",
      type: _type5
    },
    {
      name: 'b',
      doc: "",
      type: _type3
    },
    ],
    outArgs: [{
      name: 's',
      doc: "",
      type: _type3
    },
    {
      name: 'err',
      doc: "",
      type: _type14
    },
    ],
    inStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    outStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    hasInStreamHACK: false,
    hasOutStreamHACK: false,
    tags: []
  },
    
      
    {
    name: 'MethodA3',
    doc: "",
    inArgs: [{
      name: 'a',
      doc: "",
      type: _type5
    },
    ],
    outArgs: [{
      name: 's',
      doc: "",
      type: _type3
    },
    {
      name: 'err',
      doc: "",
      type: _type14
    },
    ],
    inStreamHACK: {
      name: '',
      doc: '',
      type: Types.ANY
    },
    outStreamHACK: {
      name: '',
      doc: '',
      type: _typeScalars
    },
    hasInStreamHACK: false,
    hasOutStreamHACK: true,
    tags: [new (Registry.lookupOrCreateConstructor(_type3))("tag"), new (Registry.lookupOrCreateConstructor(_type8))(6), ]
  },
    
      
    {
    name: 'MethodA4',
    doc: "",
    inArgs: [{
      name: 'a',
      doc: "",
      type: _type5
    },
    ],
    outArgs: [{
      name: '',
      doc: "",
      type: _type14
    },
    ],
    inStreamHACK: {
      name: '',
      doc: '',
      type: _type5
    },
    outStreamHACK: {
      name: '',
      doc: '',
      type: _type3
    },
    hasInStreamHACK: true,
    hasOutStreamHACK: true,
    tags: []
  },
    
  ]
};
  


module.exports = {
  types: types,
  serviceDefs: serviceDefs,
  services: services,
  consts: consts,
};
