// This file was auto-generated by the vanadium vdl tool.
var vdl = require('../../.././vdl');






module.exports = {};



// Types:
var _type1 = new vdl.Type();
var _type2 = new vdl.Type();
var _type3 = new vdl.Type();
var _type4 = new vdl.Type();
var _typeGlobError = new vdl.Type();
var _typeMountFlag = new vdl.Type();
var _typeVDLGlobReply = new vdl.Type();
var _typeVDLMountEntry = new vdl.Type();
var _typeVDLMountedServer = new vdl.Type();
var _typeerror = new vdl.Type();
_type1.kind = vdl.Kind.LIST;
_type1.name = "";
_type1.elem = vdl.Types.STRING;
_type2.kind = vdl.Kind.LIST;
_type2.name = "";
_type2.elem = _typeVDLMountedServer;
_type3.kind = vdl.Kind.ENUM;
_type3.name = "";
_type3.labels = ["NoRetry", "RetryConnection", "RetryRefetch", "RetryBackoff"];
_type4.kind = vdl.Kind.LIST;
_type4.name = "";
_type4.elem = vdl.Types.ANY;
_typeGlobError.kind = vdl.Kind.STRUCT;
_typeGlobError.name = "v.io/v23/naming.GlobError";
_typeGlobError.fields = [{name: "Name", type: vdl.Types.STRING}, {name: "Error", type: vdl.Types.ERROR}];
_typeMountFlag.kind = vdl.Kind.UINT32;
_typeMountFlag.name = "v.io/v23/naming.MountFlag";
_typeVDLGlobReply.kind = vdl.Kind.UNION;
_typeVDLGlobReply.name = "v.io/v23/naming.VDLGlobReply";
_typeVDLGlobReply.fields = [{name: "Entry", type: _typeVDLMountEntry}, {name: "Error", type: _typeGlobError}];
_typeVDLMountEntry.kind = vdl.Kind.STRUCT;
_typeVDLMountEntry.name = "v.io/v23/naming.VDLMountEntry";
_typeVDLMountEntry.fields = [{name: "Name", type: vdl.Types.STRING}, {name: "Servers", type: _type2}, {name: "MT", type: vdl.Types.BOOL}];
_typeVDLMountedServer.kind = vdl.Kind.STRUCT;
_typeVDLMountedServer.name = "v.io/v23/naming.VDLMountedServer";
_typeVDLMountedServer.fields = [{name: "Server", type: vdl.Types.STRING}, {name: "BlessingPatterns", type: _type1}, {name: "TTL", type: vdl.Types.UINT32}];
_typeerror.kind = vdl.Kind.STRUCT;
_typeerror.name = "error";
_typeerror.fields = [{name: "Id", type: vdl.Types.STRING}, {name: "RetryCode", type: _type3}, {name: "Msg", type: vdl.Types.STRING}, {name: "ParamList", type: _type4}];
_type1.freeze();
_type2.freeze();
_type3.freeze();
_type4.freeze();
_typeGlobError.freeze();
_typeMountFlag.freeze();
_typeVDLGlobReply.freeze();
_typeVDLMountEntry.freeze();
_typeVDLMountedServer.freeze();
_typeerror.freeze();
module.exports.GlobError = (vdl.Registry.lookupOrCreateConstructor(_typeGlobError));
module.exports.MountFlag = (vdl.Registry.lookupOrCreateConstructor(_typeMountFlag));
module.exports.VDLGlobReply = (vdl.Registry.lookupOrCreateConstructor(_typeVDLGlobReply));
module.exports.VDLMountEntry = (vdl.Registry.lookupOrCreateConstructor(_typeVDLMountEntry));
module.exports.VDLMountedServer = (vdl.Registry.lookupOrCreateConstructor(_typeVDLMountedServer));
module.exports.error = (vdl.Registry.lookupOrCreateConstructor(_typeerror));




// Consts:

  module.exports.Replace = new (vdl.Registry.lookupOrCreateConstructor(_typeMountFlag))(1);

  module.exports.MT = new (vdl.Registry.lookupOrCreateConstructor(_typeMountFlag))(2);



// Errors:



// Services:

   
 


