// This file was auto-generated by the veyron vdl tool.
var vom = require('../../../.././vom/vom');





module.exports = {};



// Types:
var _typeId = new vom.Type();
_typeId.kind = vom.Kind.ARRAY;
_typeId.name = "v.io/core/veyron2/uniqueid.Id";
_typeId.len = 16;
_typeId.elem = vom.Types.BYTE;
module.exports.Id = (vom.Registry.lookupOrCreateConstructor(_typeId));




// Consts:



// Errors:



function NotImplementedMethod(name) {
  throw new Error('Method ' + name + ' not implemented');
}


// Services:

   
 


