// This file was auto-generated by the veyron vdl tool.
var vom = require('vom');
// TODO(bjornick): Remove unused imports.
var Types = vom.Types;
var Type = vom.Type;
var Kind = vom.Kind;
var BigInt = vom.BigInt;
var Complex = vom.Complex;
var Builtins = vom.Builtins;
var Registry = vom.Registry;





module.exports = {};



// Types:




// Consts:




function NotImplementedMethod(name) {
  throw new Error('Method ' + name + ' not implemented');
}


// Services:

  
    
function Exp(){}
module.exports.Exp = Exp

    
      
Exp.prototype.Exp = NotImplementedMethod;
     

    
Exp.prototype._serviceDescription = {
  name: 'Exp',
  pkgPath: 'v.io/core/veyron2/vdl/testdata/arith/exp',
  doc: "",
  embeds: [],
  methods: [
    
      
    {
    name: 'Exp',
    doc: "",
    inArgs: [{
      name: 'x',
      doc: "",
      type: Types.FLOAT64
    },
    ],
    outArgs: [{
      name: '',
      doc: "",
      type: Types.FLOAT64
    },
    ],
    inStream: null,
    outStream: null,
    tags: []
  },
     
  ]
};

   
 


