// This file was auto-generated by the veyron vdl tool.
var vom = require('../../../../../../.././vom');
var makeError = require('../../../../../../.././errors/make-errors');
var actions = require('../../../../../../.././errors/actions');





var security = require('./../../../../../../core/veyron2/security');
var principal = require('./../../principal');

module.exports = {};



// Types:
var _type1 = new vom.Type();
var _type2 = new vom.Type();
var _type3 = new vom.Type();
var _type4 = new vom.Type();
var _type5 = new vom.Type();
var _type6 = new vom.Type();
var _type7 = new vom.Type();
var _type8 = new vom.Type();
var _typeCaveatValidationRequest = new vom.Type();
var _typeCaveatValidationResponse = new vom.Type();
var _typeSecurityContext = new vom.Type();
var _typeerror = new vom.Type();
_type1.kind = vom.Kind.LIST;
_type1.name = "";
_type1.elem = vom.Types.ANY;
_type2.kind = vom.Kind.LIST;
_type2.name = "";
_type2.elem = vom.Types.STRING;
_type3.kind = vom.Kind.LIST;
_type3.name = "";
_type3.elem = _type4;
_type4.kind = vom.Kind.LIST;
_type4.name = "";
_type4.elem = new security.Caveat()._type;
_type5.kind = vom.Kind.LIST;
_type5.name = "";
_type5.elem = vom.Types.BYTE;
_type6.kind = vom.Kind.LIST;
_type6.name = "";
_type6.elem = _type7;
_type7.kind = vom.Kind.OPTIONAL;
_type7.name = "";
_type7.elem = _typeerror;
_type8.kind = vom.Kind.STRUCT;
_type8.name = "";
_type8.fields = [{name: "ID", type: vom.Types.STRING}, {name: "Action", type: vom.Types.UINT32}];
_typeCaveatValidationRequest.kind = vom.Kind.STRUCT;
_typeCaveatValidationRequest.name = "v.io/wspr/veyron/services/wsprd/ipc/server.CaveatValidationRequest";
_typeCaveatValidationRequest.fields = [{name: "Ctx", type: _typeSecurityContext}, {name: "Cavs", type: _type3}];
_typeCaveatValidationResponse.kind = vom.Kind.STRUCT;
_typeCaveatValidationResponse.name = "v.io/wspr/veyron/services/wsprd/ipc/server.CaveatValidationResponse";
_typeCaveatValidationResponse.fields = [{name: "Results", type: _type6}];
_typeSecurityContext.kind = vom.Kind.STRUCT;
_typeSecurityContext.name = "v.io/wspr/veyron/services/wsprd/ipc/server.SecurityContext";
_typeSecurityContext.fields = [{name: "Method", type: vom.Types.STRING}, {name: "Name", type: vom.Types.STRING}, {name: "Suffix", type: vom.Types.STRING}, {name: "MethodTags", type: _type1}, {name: "LocalBlessings", type: new principal.BlessingsHandle()._type}, {name: "LocalBlessingStrings", type: _type2}, {name: "RemoteBlessings", type: new principal.BlessingsHandle()._type}, {name: "RemoteBlessingStrings", type: _type2}, {name: "LocalEndpoint", type: vom.Types.STRING}, {name: "RemoteEndpoint", type: vom.Types.STRING}];
_typeerror.kind = vom.Kind.STRUCT;
_typeerror.name = "error";
_typeerror.fields = [{name: "IDAction", type: _type8}, {name: "Msg", type: vom.Types.STRING}, {name: "ParamList", type: _type1}];
module.exports.CaveatValidationRequest = (vom.Registry.lookupOrCreateConstructor(_typeCaveatValidationRequest));
module.exports.CaveatValidationResponse = (vom.Registry.lookupOrCreateConstructor(_typeCaveatValidationResponse));
module.exports.SecurityContext = (vom.Registry.lookupOrCreateConstructor(_typeSecurityContext));
module.exports.error = (vom.Registry.lookupOrCreateConstructor(_typeerror));




// Consts:



// Errors:

module.exports.InvalidValidationResponseFromJavascriptError = makeError('v.io/wspr/veyron/services/wsprd/ipc/server.InvalidValidationResponseFromJavascript', actions.NO_RETRY, {
  'en': '{1:}{2:} Invalid validation response from javascript',
}, [
]);


module.exports.CaveatValidationTimeoutError = makeError('v.io/wspr/veyron/services/wsprd/ipc/server.CaveatValidationTimeout', actions.NO_RETRY, {
  'en': '{1:}{2:} Caveat validation timed out',
}, [
]);




// Services:

   
 


