// This file was auto-generated by the veyron vdl tool.
var vom = require('../../../../.././vom/vom');






module.exports = {};



// Types:
var _typedataRep = new vom.Type();
_typedataRep.kind = vom.Kind.ENUM;
_typedataRep.name = "v.io/core/veyron2/vom/vom.dataRep";
_typedataRep.labels = ["Hex", "Binary"];
module.exports.dataRep = (vom.Registry.lookupOrCreateConstructor(_typedataRep));




// Consts:



// Errors:



// Services:

   
 


