// This file was auto-generated by the vanadium vdl tool.
// Source: cache.vdl

package test_service

import (
	// VDL system imports
	"io"
	"v.io/v23"
	"v.io/v23/context"
	"v.io/v23/ipc"
	"v.io/v23/vdl"
)

// KeyPageResult is a page of 10 keys.
type KeyPageResult [10]string

func (KeyPageResult) __VDLReflect(struct {
	Name string "test_service.KeyPageResult"
}) {
}

// KeyValuePair is a representation of a cached key and value pair.
type KeyValuePair struct {
	Key   string
	Value *vdl.Value
}

func (KeyValuePair) __VDLReflect(struct {
	Name string "test_service.KeyValuePair"
}) {
}

func init() {
	vdl.Register((*KeyPageResult)(nil))
	vdl.Register((*KeyValuePair)(nil))
}

// CacheClientMethods is the client interface
// containing Cache methods.
//
// A Cache service mimics the memcache interface.
type CacheClientMethods interface {
	// Set sets a value for a key.
	Set(ctx *context.T, key string, value *vdl.Value, opts ...ipc.CallOpt) error
	// Get returns the value for a key.  If the value is not found, returns
	// a not found error.
	Get(ctx *context.T, key string, opts ...ipc.CallOpt) (*vdl.Value, error)
	// Same as Get, but casts the return argument to an byte.
	GetAsByte(ctx *context.T, key string, opts ...ipc.CallOpt) (byte, error)
	// Same as Get, but casts the return argument to an int32.
	GetAsInt32(ctx *context.T, key string, opts ...ipc.CallOpt) (int32, error)
	// Same as Get, but casts the return argument to an int64.
	GetAsInt64(ctx *context.T, key string, opts ...ipc.CallOpt) (int64, error)
	// Same as Get, but casts the return argument to an uint32.
	GetAsUint32(ctx *context.T, key string, opts ...ipc.CallOpt) (uint32, error)
	// Same as Get, but casts the return argument to an uint64.
	GetAsUint64(ctx *context.T, key string, opts ...ipc.CallOpt) (uint64, error)
	// Same as Get, but casts the return argument to an float32.
	GetAsFloat32(ctx *context.T, key string, opts ...ipc.CallOpt) (float32, error)
	// Same as Get, but casts the return argument to an float64.
	GetAsFloat64(ctx *context.T, key string, opts ...ipc.CallOpt) (float64, error)
	// Same as Get, but casts the return argument to a string.
	GetAsString(ctx *context.T, key string, opts ...ipc.CallOpt) (string, error)
	// Same as Get, but casts the return argument to a bool.
	GetAsBool(ctx *context.T, key string, opts ...ipc.CallOpt) (bool, error)
	// Same as Get, but casts the return argument to an error.
	GetAsError(ctx *context.T, key string, opts ...ipc.CallOpt) (error, error)
	// AsMap returns the full contents of the cache as a map.
	AsMap(*context.T, ...ipc.CallOpt) (map[string]*vdl.Value, error)
	// KeyValuePairs returns the full contents of the cache as a slice of pairs.
	KeyValuePairs(*context.T, ...ipc.CallOpt) ([]KeyValuePair, error)
	// MostRecentSet returns the key and value and the timestamp for the most
	// recent set operation
	// TODO(bprosnitz) support type types and change time to native time type
	MostRecentSet(*context.T, ...ipc.CallOpt) (value KeyValuePair, time int64, err error)
	// KeyPage indexes into the keys (in alphanumerically sorted order) and
	// returns the indexth page of 10 keys.
	KeyPage(ctx *context.T, index int64, opts ...ipc.CallOpt) (KeyPageResult, error)
	// Size returns the total number of entries in the cache.
	Size(*context.T, ...ipc.CallOpt) (int64, error)
	// MultiGet sets up a stream that allows fetching multiple keys.
	MultiGet(*context.T, ...ipc.CallOpt) (CacheMultiGetClientCall, error)
}

// CacheClientStub adds universal methods to CacheClientMethods.
type CacheClientStub interface {
	CacheClientMethods
	ipc.UniversalServiceMethods
}

// CacheClient returns a client stub for Cache.
func CacheClient(name string, opts ...ipc.BindOpt) CacheClientStub {
	var client ipc.Client
	for _, opt := range opts {
		if clientOpt, ok := opt.(ipc.Client); ok {
			client = clientOpt
		}
	}
	return implCacheClientStub{name, client}
}

type implCacheClientStub struct {
	name   string
	client ipc.Client
}

func (c implCacheClientStub) c(ctx *context.T) ipc.Client {
	if c.client != nil {
		return c.client
	}
	return v23.GetClient(ctx)
}

func (c implCacheClientStub) Set(ctx *context.T, i0 string, i1 *vdl.Value, opts ...ipc.CallOpt) (err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "Set", []interface{}{i0, i1}, opts...); err != nil {
		return
	}
	err = call.Finish()
	return
}

func (c implCacheClientStub) Get(ctx *context.T, i0 string, opts ...ipc.CallOpt) (o0 *vdl.Value, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "Get", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) GetAsByte(ctx *context.T, i0 string, opts ...ipc.CallOpt) (o0 byte, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "GetAsByte", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) GetAsInt32(ctx *context.T, i0 string, opts ...ipc.CallOpt) (o0 int32, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "GetAsInt32", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) GetAsInt64(ctx *context.T, i0 string, opts ...ipc.CallOpt) (o0 int64, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "GetAsInt64", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) GetAsUint32(ctx *context.T, i0 string, opts ...ipc.CallOpt) (o0 uint32, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "GetAsUint32", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) GetAsUint64(ctx *context.T, i0 string, opts ...ipc.CallOpt) (o0 uint64, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "GetAsUint64", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) GetAsFloat32(ctx *context.T, i0 string, opts ...ipc.CallOpt) (o0 float32, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "GetAsFloat32", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) GetAsFloat64(ctx *context.T, i0 string, opts ...ipc.CallOpt) (o0 float64, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "GetAsFloat64", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) GetAsString(ctx *context.T, i0 string, opts ...ipc.CallOpt) (o0 string, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "GetAsString", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) GetAsBool(ctx *context.T, i0 string, opts ...ipc.CallOpt) (o0 bool, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "GetAsBool", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) GetAsError(ctx *context.T, i0 string, opts ...ipc.CallOpt) (o0 error, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "GetAsError", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) AsMap(ctx *context.T, opts ...ipc.CallOpt) (o0 map[string]*vdl.Value, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "AsMap", nil, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) KeyValuePairs(ctx *context.T, opts ...ipc.CallOpt) (o0 []KeyValuePair, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "KeyValuePairs", nil, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) MostRecentSet(ctx *context.T, opts ...ipc.CallOpt) (o0 KeyValuePair, o1 int64, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "MostRecentSet", nil, opts...); err != nil {
		return
	}
	err = call.Finish(&o0, &o1)
	return
}

func (c implCacheClientStub) KeyPage(ctx *context.T, i0 int64, opts ...ipc.CallOpt) (o0 KeyPageResult, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "KeyPage", []interface{}{i0}, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) Size(ctx *context.T, opts ...ipc.CallOpt) (o0 int64, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "Size", nil, opts...); err != nil {
		return
	}
	err = call.Finish(&o0)
	return
}

func (c implCacheClientStub) MultiGet(ctx *context.T, opts ...ipc.CallOpt) (ocall CacheMultiGetClientCall, err error) {
	var call ipc.ClientCall
	if call, err = c.c(ctx).StartCall(ctx, c.name, "MultiGet", nil, opts...); err != nil {
		return
	}
	ocall = &implCacheMultiGetClientCall{ClientCall: call}
	return
}

// CacheMultiGetClientStream is the client stream for Cache.MultiGet.
type CacheMultiGetClientStream interface {
	// RecvStream returns the receiver side of the Cache.MultiGet client stream.
	RecvStream() interface {
		// Advance stages an item so that it may be retrieved via Value.  Returns
		// true iff there is an item to retrieve.  Advance must be called before
		// Value is called.  May block if an item is not available.
		Advance() bool
		// Value returns the item that was staged by Advance.  May panic if Advance
		// returned false or was not called.  Never blocks.
		Value() *vdl.Value
		// Err returns any error encountered by Advance.  Never blocks.
		Err() error
	}
	// SendStream returns the send side of the Cache.MultiGet client stream.
	SendStream() interface {
		// Send places the item onto the output stream.  Returns errors
		// encountered while sending, or if Send is called after Close or
		// the stream has been canceled.  Blocks if there is no buffer
		// space; will unblock when buffer space is available or after
		// the stream has been canceled.
		Send(item string) error
		// Close indicates to the server that no more items will be sent;
		// server Recv calls will receive io.EOF after all sent items.
		// This is an optional call - e.g. a client might call Close if it
		// needs to continue receiving items from the server after it's
		// done sending.  Returns errors encountered while closing, or if
		// Close is called after the stream has been canceled.  Like Send,
		// blocks if there is no buffer space available.
		Close() error
	}
}

// CacheMultiGetClientCall represents the call returned from Cache.MultiGet.
type CacheMultiGetClientCall interface {
	CacheMultiGetClientStream
	// Finish performs the equivalent of SendStream().Close, then blocks until
	// the server is done, and returns the positional return values for the call.
	//
	// Finish returns immediately if the call has been canceled; depending on the
	// timing the output could either be an error signaling cancelation, or the
	// valid positional return values from the server.
	//
	// Calling Finish is mandatory for releasing stream resources, unless the call
	// has been canceled or any of the other methods return an error.  Finish should
	// be called at most once.
	Finish() error
}

type implCacheMultiGetClientCall struct {
	ipc.ClientCall
	valRecv *vdl.Value
	errRecv error
}

func (c *implCacheMultiGetClientCall) RecvStream() interface {
	Advance() bool
	Value() *vdl.Value
	Err() error
} {
	return implCacheMultiGetClientCallRecv{c}
}

type implCacheMultiGetClientCallRecv struct {
	c *implCacheMultiGetClientCall
}

func (c implCacheMultiGetClientCallRecv) Advance() bool {
	c.c.valRecv = nil
	c.c.errRecv = c.c.Recv(&c.c.valRecv)
	return c.c.errRecv == nil
}
func (c implCacheMultiGetClientCallRecv) Value() *vdl.Value {
	return c.c.valRecv
}
func (c implCacheMultiGetClientCallRecv) Err() error {
	if c.c.errRecv == io.EOF {
		return nil
	}
	return c.c.errRecv
}
func (c *implCacheMultiGetClientCall) SendStream() interface {
	Send(item string) error
	Close() error
} {
	return implCacheMultiGetClientCallSend{c}
}

type implCacheMultiGetClientCallSend struct {
	c *implCacheMultiGetClientCall
}

func (c implCacheMultiGetClientCallSend) Send(item string) error {
	return c.c.Send(item)
}
func (c implCacheMultiGetClientCallSend) Close() error {
	return c.c.CloseSend()
}
func (c *implCacheMultiGetClientCall) Finish() (err error) {
	err = c.ClientCall.Finish()
	return
}

// CacheServerMethods is the interface a server writer
// implements for Cache.
//
// A Cache service mimics the memcache interface.
type CacheServerMethods interface {
	// Set sets a value for a key.
	Set(call ipc.ServerCall, key string, value *vdl.Value) error
	// Get returns the value for a key.  If the value is not found, returns
	// a not found error.
	Get(call ipc.ServerCall, key string) (*vdl.Value, error)
	// Same as Get, but casts the return argument to an byte.
	GetAsByte(call ipc.ServerCall, key string) (byte, error)
	// Same as Get, but casts the return argument to an int32.
	GetAsInt32(call ipc.ServerCall, key string) (int32, error)
	// Same as Get, but casts the return argument to an int64.
	GetAsInt64(call ipc.ServerCall, key string) (int64, error)
	// Same as Get, but casts the return argument to an uint32.
	GetAsUint32(call ipc.ServerCall, key string) (uint32, error)
	// Same as Get, but casts the return argument to an uint64.
	GetAsUint64(call ipc.ServerCall, key string) (uint64, error)
	// Same as Get, but casts the return argument to an float32.
	GetAsFloat32(call ipc.ServerCall, key string) (float32, error)
	// Same as Get, but casts the return argument to an float64.
	GetAsFloat64(call ipc.ServerCall, key string) (float64, error)
	// Same as Get, but casts the return argument to a string.
	GetAsString(call ipc.ServerCall, key string) (string, error)
	// Same as Get, but casts the return argument to a bool.
	GetAsBool(call ipc.ServerCall, key string) (bool, error)
	// Same as Get, but casts the return argument to an error.
	GetAsError(call ipc.ServerCall, key string) (error, error)
	// AsMap returns the full contents of the cache as a map.
	AsMap(ipc.ServerCall) (map[string]*vdl.Value, error)
	// KeyValuePairs returns the full contents of the cache as a slice of pairs.
	KeyValuePairs(ipc.ServerCall) ([]KeyValuePair, error)
	// MostRecentSet returns the key and value and the timestamp for the most
	// recent set operation
	// TODO(bprosnitz) support type types and change time to native time type
	MostRecentSet(ipc.ServerCall) (value KeyValuePair, time int64, err error)
	// KeyPage indexes into the keys (in alphanumerically sorted order) and
	// returns the indexth page of 10 keys.
	KeyPage(call ipc.ServerCall, index int64) (KeyPageResult, error)
	// Size returns the total number of entries in the cache.
	Size(ipc.ServerCall) (int64, error)
	// MultiGet sets up a stream that allows fetching multiple keys.
	MultiGet(CacheMultiGetServerCall) error
}

// CacheServerStubMethods is the server interface containing
// Cache methods, as expected by ipc.Server.
// The only difference between this interface and CacheServerMethods
// is the streaming methods.
type CacheServerStubMethods interface {
	// Set sets a value for a key.
	Set(call ipc.ServerCall, key string, value *vdl.Value) error
	// Get returns the value for a key.  If the value is not found, returns
	// a not found error.
	Get(call ipc.ServerCall, key string) (*vdl.Value, error)
	// Same as Get, but casts the return argument to an byte.
	GetAsByte(call ipc.ServerCall, key string) (byte, error)
	// Same as Get, but casts the return argument to an int32.
	GetAsInt32(call ipc.ServerCall, key string) (int32, error)
	// Same as Get, but casts the return argument to an int64.
	GetAsInt64(call ipc.ServerCall, key string) (int64, error)
	// Same as Get, but casts the return argument to an uint32.
	GetAsUint32(call ipc.ServerCall, key string) (uint32, error)
	// Same as Get, but casts the return argument to an uint64.
	GetAsUint64(call ipc.ServerCall, key string) (uint64, error)
	// Same as Get, but casts the return argument to an float32.
	GetAsFloat32(call ipc.ServerCall, key string) (float32, error)
	// Same as Get, but casts the return argument to an float64.
	GetAsFloat64(call ipc.ServerCall, key string) (float64, error)
	// Same as Get, but casts the return argument to a string.
	GetAsString(call ipc.ServerCall, key string) (string, error)
	// Same as Get, but casts the return argument to a bool.
	GetAsBool(call ipc.ServerCall, key string) (bool, error)
	// Same as Get, but casts the return argument to an error.
	GetAsError(call ipc.ServerCall, key string) (error, error)
	// AsMap returns the full contents of the cache as a map.
	AsMap(ipc.ServerCall) (map[string]*vdl.Value, error)
	// KeyValuePairs returns the full contents of the cache as a slice of pairs.
	KeyValuePairs(ipc.ServerCall) ([]KeyValuePair, error)
	// MostRecentSet returns the key and value and the timestamp for the most
	// recent set operation
	// TODO(bprosnitz) support type types and change time to native time type
	MostRecentSet(ipc.ServerCall) (value KeyValuePair, time int64, err error)
	// KeyPage indexes into the keys (in alphanumerically sorted order) and
	// returns the indexth page of 10 keys.
	KeyPage(call ipc.ServerCall, index int64) (KeyPageResult, error)
	// Size returns the total number of entries in the cache.
	Size(ipc.ServerCall) (int64, error)
	// MultiGet sets up a stream that allows fetching multiple keys.
	MultiGet(*CacheMultiGetServerCallStub) error
}

// CacheServerStub adds universal methods to CacheServerStubMethods.
type CacheServerStub interface {
	CacheServerStubMethods
	// Describe the Cache interfaces.
	Describe__() []ipc.InterfaceDesc
}

// CacheServer returns a server stub for Cache.
// It converts an implementation of CacheServerMethods into
// an object that may be used by ipc.Server.
func CacheServer(impl CacheServerMethods) CacheServerStub {
	stub := implCacheServerStub{
		impl: impl,
	}
	// Initialize GlobState; always check the stub itself first, to handle the
	// case where the user has the Glob method defined in their VDL source.
	if gs := ipc.NewGlobState(stub); gs != nil {
		stub.gs = gs
	} else if gs := ipc.NewGlobState(impl); gs != nil {
		stub.gs = gs
	}
	return stub
}

type implCacheServerStub struct {
	impl CacheServerMethods
	gs   *ipc.GlobState
}

func (s implCacheServerStub) Set(call ipc.ServerCall, i0 string, i1 *vdl.Value) error {
	return s.impl.Set(call, i0, i1)
}

func (s implCacheServerStub) Get(call ipc.ServerCall, i0 string) (*vdl.Value, error) {
	return s.impl.Get(call, i0)
}

func (s implCacheServerStub) GetAsByte(call ipc.ServerCall, i0 string) (byte, error) {
	return s.impl.GetAsByte(call, i0)
}

func (s implCacheServerStub) GetAsInt32(call ipc.ServerCall, i0 string) (int32, error) {
	return s.impl.GetAsInt32(call, i0)
}

func (s implCacheServerStub) GetAsInt64(call ipc.ServerCall, i0 string) (int64, error) {
	return s.impl.GetAsInt64(call, i0)
}

func (s implCacheServerStub) GetAsUint32(call ipc.ServerCall, i0 string) (uint32, error) {
	return s.impl.GetAsUint32(call, i0)
}

func (s implCacheServerStub) GetAsUint64(call ipc.ServerCall, i0 string) (uint64, error) {
	return s.impl.GetAsUint64(call, i0)
}

func (s implCacheServerStub) GetAsFloat32(call ipc.ServerCall, i0 string) (float32, error) {
	return s.impl.GetAsFloat32(call, i0)
}

func (s implCacheServerStub) GetAsFloat64(call ipc.ServerCall, i0 string) (float64, error) {
	return s.impl.GetAsFloat64(call, i0)
}

func (s implCacheServerStub) GetAsString(call ipc.ServerCall, i0 string) (string, error) {
	return s.impl.GetAsString(call, i0)
}

func (s implCacheServerStub) GetAsBool(call ipc.ServerCall, i0 string) (bool, error) {
	return s.impl.GetAsBool(call, i0)
}

func (s implCacheServerStub) GetAsError(call ipc.ServerCall, i0 string) (error, error) {
	return s.impl.GetAsError(call, i0)
}

func (s implCacheServerStub) AsMap(call ipc.ServerCall) (map[string]*vdl.Value, error) {
	return s.impl.AsMap(call)
}

func (s implCacheServerStub) KeyValuePairs(call ipc.ServerCall) ([]KeyValuePair, error) {
	return s.impl.KeyValuePairs(call)
}

func (s implCacheServerStub) MostRecentSet(call ipc.ServerCall) (KeyValuePair, int64, error) {
	return s.impl.MostRecentSet(call)
}

func (s implCacheServerStub) KeyPage(call ipc.ServerCall, i0 int64) (KeyPageResult, error) {
	return s.impl.KeyPage(call, i0)
}

func (s implCacheServerStub) Size(call ipc.ServerCall) (int64, error) {
	return s.impl.Size(call)
}

func (s implCacheServerStub) MultiGet(call *CacheMultiGetServerCallStub) error {
	return s.impl.MultiGet(call)
}

func (s implCacheServerStub) Globber() *ipc.GlobState {
	return s.gs
}

func (s implCacheServerStub) Describe__() []ipc.InterfaceDesc {
	return []ipc.InterfaceDesc{CacheDesc}
}

// CacheDesc describes the Cache interface.
var CacheDesc ipc.InterfaceDesc = descCache

// descCache hides the desc to keep godoc clean.
var descCache = ipc.InterfaceDesc{
	Name:    "Cache",
	PkgPath: "test_service",
	Doc:     "// A Cache service mimics the memcache interface.",
	Methods: []ipc.MethodDesc{
		{
			Name: "Set",
			Doc:  "// Set sets a value for a key.",
			InArgs: []ipc.ArgDesc{
				{"key", ``},   // string
				{"value", ``}, // *vdl.Value
			},
		},
		{
			Name: "Get",
			Doc:  "// Get returns the value for a key.  If the value is not found, returns\n// a not found error.",
			InArgs: []ipc.ArgDesc{
				{"key", ``}, // string
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // *vdl.Value
			},
		},
		{
			Name: "GetAsByte",
			Doc:  "// Same as Get, but casts the return argument to an byte.",
			InArgs: []ipc.ArgDesc{
				{"key", ``}, // string
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // byte
			},
		},
		{
			Name: "GetAsInt32",
			Doc:  "// Same as Get, but casts the return argument to an int32.",
			InArgs: []ipc.ArgDesc{
				{"key", ``}, // string
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // int32
			},
		},
		{
			Name: "GetAsInt64",
			Doc:  "// Same as Get, but casts the return argument to an int64.",
			InArgs: []ipc.ArgDesc{
				{"key", ``}, // string
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // int64
			},
		},
		{
			Name: "GetAsUint32",
			Doc:  "// Same as Get, but casts the return argument to an uint32.",
			InArgs: []ipc.ArgDesc{
				{"key", ``}, // string
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // uint32
			},
		},
		{
			Name: "GetAsUint64",
			Doc:  "// Same as Get, but casts the return argument to an uint64.",
			InArgs: []ipc.ArgDesc{
				{"key", ``}, // string
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // uint64
			},
		},
		{
			Name: "GetAsFloat32",
			Doc:  "// Same as Get, but casts the return argument to an float32.",
			InArgs: []ipc.ArgDesc{
				{"key", ``}, // string
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // float32
			},
		},
		{
			Name: "GetAsFloat64",
			Doc:  "// Same as Get, but casts the return argument to an float64.",
			InArgs: []ipc.ArgDesc{
				{"key", ``}, // string
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // float64
			},
		},
		{
			Name: "GetAsString",
			Doc:  "// Same as Get, but casts the return argument to a string.",
			InArgs: []ipc.ArgDesc{
				{"key", ``}, // string
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // string
			},
		},
		{
			Name: "GetAsBool",
			Doc:  "// Same as Get, but casts the return argument to a bool.",
			InArgs: []ipc.ArgDesc{
				{"key", ``}, // string
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // bool
			},
		},
		{
			Name: "GetAsError",
			Doc:  "// Same as Get, but casts the return argument to an error.",
			InArgs: []ipc.ArgDesc{
				{"key", ``}, // string
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // error
			},
		},
		{
			Name: "AsMap",
			Doc:  "// AsMap returns the full contents of the cache as a map.",
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // map[string]*vdl.Value
			},
		},
		{
			Name: "KeyValuePairs",
			Doc:  "// KeyValuePairs returns the full contents of the cache as a slice of pairs.",
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // []KeyValuePair
			},
		},
		{
			Name: "MostRecentSet",
			Doc:  "// MostRecentSet returns the key and value and the timestamp for the most\n// recent set operation\n// TODO(bprosnitz) support type types and change time to native time type",
			OutArgs: []ipc.ArgDesc{
				{"value", ``}, // KeyValuePair
				{"time", ``},  // int64
			},
		},
		{
			Name: "KeyPage",
			Doc:  "// KeyPage indexes into the keys (in alphanumerically sorted order) and\n// returns the indexth page of 10 keys.",
			InArgs: []ipc.ArgDesc{
				{"index", ``}, // int64
			},
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // KeyPageResult
			},
		},
		{
			Name: "Size",
			Doc:  "// Size returns the total number of entries in the cache.",
			OutArgs: []ipc.ArgDesc{
				{"", ``}, // int64
			},
		},
		{
			Name: "MultiGet",
			Doc:  "// MultiGet sets up a stream that allows fetching multiple keys.",
		},
	},
}

// CacheMultiGetServerStream is the server stream for Cache.MultiGet.
type CacheMultiGetServerStream interface {
	// RecvStream returns the receiver side of the Cache.MultiGet server stream.
	RecvStream() interface {
		// Advance stages an item so that it may be retrieved via Value.  Returns
		// true iff there is an item to retrieve.  Advance must be called before
		// Value is called.  May block if an item is not available.
		Advance() bool
		// Value returns the item that was staged by Advance.  May panic if Advance
		// returned false or was not called.  Never blocks.
		Value() string
		// Err returns any error encountered by Advance.  Never blocks.
		Err() error
	}
	// SendStream returns the send side of the Cache.MultiGet server stream.
	SendStream() interface {
		// Send places the item onto the output stream.  Returns errors encountered
		// while sending.  Blocks if there is no buffer space; will unblock when
		// buffer space is available.
		Send(item *vdl.Value) error
	}
}

// CacheMultiGetServerCall represents the context passed to Cache.MultiGet.
type CacheMultiGetServerCall interface {
	ipc.ServerCall
	CacheMultiGetServerStream
}

// CacheMultiGetServerCallStub is a wrapper that converts ipc.StreamServerCall into
// a typesafe stub that implements CacheMultiGetServerCall.
type CacheMultiGetServerCallStub struct {
	ipc.StreamServerCall
	valRecv string
	errRecv error
}

// Init initializes CacheMultiGetServerCallStub from ipc.StreamServerCall.
func (s *CacheMultiGetServerCallStub) Init(call ipc.StreamServerCall) {
	s.StreamServerCall = call
}

// RecvStream returns the receiver side of the Cache.MultiGet server stream.
func (s *CacheMultiGetServerCallStub) RecvStream() interface {
	Advance() bool
	Value() string
	Err() error
} {
	return implCacheMultiGetServerCallRecv{s}
}

type implCacheMultiGetServerCallRecv struct {
	s *CacheMultiGetServerCallStub
}

func (s implCacheMultiGetServerCallRecv) Advance() bool {
	s.s.errRecv = s.s.Recv(&s.s.valRecv)
	return s.s.errRecv == nil
}
func (s implCacheMultiGetServerCallRecv) Value() string {
	return s.s.valRecv
}
func (s implCacheMultiGetServerCallRecv) Err() error {
	if s.s.errRecv == io.EOF {
		return nil
	}
	return s.s.errRecv
}

// SendStream returns the send side of the Cache.MultiGet server stream.
func (s *CacheMultiGetServerCallStub) SendStream() interface {
	Send(item *vdl.Value) error
} {
	return implCacheMultiGetServerCallSend{s}
}

type implCacheMultiGetServerCallSend struct {
	s *CacheMultiGetServerCallStub
}

func (s implCacheMultiGetServerCallSend) Send(item *vdl.Value) error {
	return s.s.Send(item)
}
