// This file was auto-generated by the veyron vdl tool.
// Source: cancel_collector.vdl

package test_service

import (
	// The non-user imports are prefixed with "_gen_" to prevent collisions.
	_gen_veyron2 "veyron.io/veyron/veyron2"
	_gen_context "veyron.io/veyron/veyron2/context"
	_gen_ipc "veyron.io/veyron/veyron2/ipc"
	_gen_naming "veyron.io/veyron/veyron2/naming"
	_gen_vdlutil "veyron.io/veyron/veyron2/vdl/vdlutil"
	_gen_wiretype "veyron.io/veyron/veyron2/wiretype"
)

// TODO(toddw): Remove this line once the new signature support is done.
// It corrects a bug where _gen_wiretype is unused in VDL pacakges where only
// bootstrap types are used on interfaces.
const _ = _gen_wiretype.TypeIDInvalid

// CancelCollector is a test interface for use in testing cancellation and deadlines.
// CancelCollector is the interface the client binds and uses.
// CancelCollector_ExcludingUniversal is the interface without internal framework-added methods
// to enable embedding without method collisions.  Not to be used directly by clients.
type CancelCollector_ExcludingUniversal interface {
	// A function that never returns, but records the status of the given key.
	NeverReturn(ctx _gen_context.T, key int64, opts ..._gen_ipc.CallOpt) (err error)
	// Wait for the call with the given key to have the given status.  Possible statuses are:
	// "running", and, "cancelled".  Returns the number of nanoseconds left on
	// the deadline of the specified call when the call first began.
	WaitForStatus(ctx _gen_context.T, key int64, status string, opts ..._gen_ipc.CallOpt) (reply int64, err error)
}
type CancelCollector interface {
	_gen_ipc.UniversalServiceMethods
	CancelCollector_ExcludingUniversal
}

// CancelCollectorService is the interface the server implements.
type CancelCollectorService interface {

	// A function that never returns, but records the status of the given key.
	NeverReturn(context _gen_ipc.ServerContext, key int64) (err error)
	// Wait for the call with the given key to have the given status.  Possible statuses are:
	// "running", and, "cancelled".  Returns the number of nanoseconds left on
	// the deadline of the specified call when the call first began.
	WaitForStatus(context _gen_ipc.ServerContext, key int64, status string) (reply int64, err error)
}

// BindCancelCollector returns the client stub implementing the CancelCollector
// interface.
//
// If no _gen_ipc.Client is specified, the default _gen_ipc.Client in the
// global Runtime is used.
func BindCancelCollector(name string, opts ..._gen_ipc.BindOpt) (CancelCollector, error) {
	var client _gen_ipc.Client
	switch len(opts) {
	case 0:
		// Do nothing.
	case 1:
		if clientOpt, ok := opts[0].(_gen_ipc.Client); opts[0] == nil || ok {
			client = clientOpt
		} else {
			return nil, _gen_vdlutil.ErrUnrecognizedOption
		}
	default:
		return nil, _gen_vdlutil.ErrTooManyOptionsToBind
	}
	stub := &clientStubCancelCollector{defaultClient: client, name: name}

	return stub, nil
}

// NewServerCancelCollector creates a new server stub.
//
// It takes a regular server implementing the CancelCollectorService
// interface, and returns a new server stub.
func NewServerCancelCollector(server CancelCollectorService) interface{} {
	return &ServerStubCancelCollector{
		service: server,
	}
}

// clientStubCancelCollector implements CancelCollector.
type clientStubCancelCollector struct {
	defaultClient _gen_ipc.Client
	name          string
}

func (__gen_c *clientStubCancelCollector) client(ctx _gen_context.T) _gen_ipc.Client {
	if __gen_c.defaultClient != nil {
		return __gen_c.defaultClient
	}
	return _gen_veyron2.RuntimeFromContext(ctx).Client()
}

func (__gen_c *clientStubCancelCollector) NeverReturn(ctx _gen_context.T, key int64, opts ..._gen_ipc.CallOpt) (err error) {
	var call _gen_ipc.Call
	if call, err = __gen_c.client(ctx).StartCall(ctx, __gen_c.name, "NeverReturn", []interface{}{key}, opts...); err != nil {
		return
	}
	if ierr := call.Finish(&err); ierr != nil {
		err = ierr
	}
	return
}

func (__gen_c *clientStubCancelCollector) WaitForStatus(ctx _gen_context.T, key int64, status string, opts ..._gen_ipc.CallOpt) (reply int64, err error) {
	var call _gen_ipc.Call
	if call, err = __gen_c.client(ctx).StartCall(ctx, __gen_c.name, "WaitForStatus", []interface{}{key, status}, opts...); err != nil {
		return
	}
	if ierr := call.Finish(&reply, &err); ierr != nil {
		err = ierr
	}
	return
}

func (__gen_c *clientStubCancelCollector) UnresolveStep(ctx _gen_context.T, opts ..._gen_ipc.CallOpt) (reply []string, err error) {
	var call _gen_ipc.Call
	if call, err = __gen_c.client(ctx).StartCall(ctx, __gen_c.name, "UnresolveStep", nil, opts...); err != nil {
		return
	}
	if ierr := call.Finish(&reply, &err); ierr != nil {
		err = ierr
	}
	return
}

func (__gen_c *clientStubCancelCollector) Signature(ctx _gen_context.T, opts ..._gen_ipc.CallOpt) (reply _gen_ipc.ServiceSignature, err error) {
	var call _gen_ipc.Call
	if call, err = __gen_c.client(ctx).StartCall(ctx, __gen_c.name, "Signature", nil, opts...); err != nil {
		return
	}
	if ierr := call.Finish(&reply, &err); ierr != nil {
		err = ierr
	}
	return
}

func (__gen_c *clientStubCancelCollector) GetMethodTags(ctx _gen_context.T, method string, opts ..._gen_ipc.CallOpt) (reply []interface{}, err error) {
	var call _gen_ipc.Call
	if call, err = __gen_c.client(ctx).StartCall(ctx, __gen_c.name, "GetMethodTags", []interface{}{method}, opts...); err != nil {
		return
	}
	if ierr := call.Finish(&reply, &err); ierr != nil {
		err = ierr
	}
	return
}

// ServerStubCancelCollector wraps a server that implements
// CancelCollectorService and provides an object that satisfies
// the requirements of veyron2/ipc.ReflectInvoker.
type ServerStubCancelCollector struct {
	service CancelCollectorService
}

func (__gen_s *ServerStubCancelCollector) GetMethodTags(call _gen_ipc.ServerCall, method string) ([]interface{}, error) {
	// TODO(bprosnitz) GetMethodTags() will be replaces with Signature().
	// Note: This exhibits some weird behavior like returning a nil error if the method isn't found.
	// This will change when it is replaced with Signature().
	switch method {
	case "NeverReturn":
		return []interface{}{}, nil
	case "WaitForStatus":
		return []interface{}{}, nil
	default:
		return nil, nil
	}
}

func (__gen_s *ServerStubCancelCollector) Signature(call _gen_ipc.ServerCall) (_gen_ipc.ServiceSignature, error) {
	result := _gen_ipc.ServiceSignature{Methods: make(map[string]_gen_ipc.MethodSignature)}
	result.Methods["NeverReturn"] = _gen_ipc.MethodSignature{
		InArgs: []_gen_ipc.MethodArgument{
			{Name: "key", Type: 37},
		},
		OutArgs: []_gen_ipc.MethodArgument{
			{Name: "", Type: 65},
		},
	}
	result.Methods["WaitForStatus"] = _gen_ipc.MethodSignature{
		InArgs: []_gen_ipc.MethodArgument{
			{Name: "key", Type: 37},
			{Name: "status", Type: 3},
		},
		OutArgs: []_gen_ipc.MethodArgument{
			{Name: "timeout", Type: 37},
			{Name: "err", Type: 65},
		},
	}

	result.TypeDefs = []_gen_vdlutil.Any{
		_gen_wiretype.NamedPrimitiveType{Type: 0x1, Name: "error", Tags: []string(nil)}}

	return result, nil
}

func (__gen_s *ServerStubCancelCollector) UnresolveStep(call _gen_ipc.ServerCall) (reply []string, err error) {
	if unresolver, ok := __gen_s.service.(_gen_ipc.Unresolver); ok {
		return unresolver.UnresolveStep(call)
	}
	if call.Server() == nil {
		return
	}
	var published []string
	if published, err = call.Server().Published(); err != nil || published == nil {
		return
	}
	reply = make([]string, len(published))
	for i, p := range published {
		reply[i] = _gen_naming.Join(p, call.Name())
	}
	return
}

func (__gen_s *ServerStubCancelCollector) NeverReturn(call _gen_ipc.ServerCall, key int64) (err error) {
	err = __gen_s.service.NeverReturn(call, key)
	return
}

func (__gen_s *ServerStubCancelCollector) WaitForStatus(call _gen_ipc.ServerCall, key int64, status string) (reply int64, err error) {
	reply, err = __gen_s.service.WaitForStatus(call, key, status)
	return
}
