// This file was auto-generated by the veyron vdl tool.
var vom = require('vom');
// TODO(bjornick): Remove unused imports.
var Types = vom.Types;
var Type = vom.Type;
var Kind = vom.Kind;
var BigInt = vom.BigInt;
var Complex = vom.Complex;
var Builtins = vom.Builtins;
var Registry = vom.Registry;






var types = {};
var _typeID = new Type();
_typeID.kind = Kind.ARRAY;
_typeID.name = "veyron.io/veyron/veyron2/uniqueid.ID";
_typeID.len = 16;
_typeID.elem = Types.BYTE;
types.ID = Registry.lookupOrCreateConstructor(_typeID, "ID");



var consts = { 
};


function NotImplementedMethod(name) {
  throw new Error('Method ' + name + ' not implemented');
}


var services = {
package: 'veyron.io/veyron/veyron2/uniqueid',

};


var serviceDefs = {
  package: 'veyron.io/veyron/veyron2/uniqueid',

  

};



  


module.exports = {
  types: types,
  serviceDefs: serviceDefs,
  services: services,
  consts: consts,
};
