// This file was auto-generated by the veyron vdl tool.
var vom = require('../../../../../.././vom/vom');





module.exports = {};



// Types:
var _typeCaveat = new vom.Type();
_typeCaveat.kind = vom.Kind.STRUCT;
_typeCaveat.name = "v.io/wspr/veyron/services/wsprd/account.Caveat";
_typeCaveat.fields = [{name: "Type", type: vom.Types.STRING}, {name: "Args", type: vom.Types.STRING}];
module.exports.Caveat = (vom.Registry.lookupOrCreateConstructor(_typeCaveat));




// Consts:



// Errors:



function NotImplementedMethod(name) {
  throw new Error('Method ' + name + ' not implemented');
}


// Services:

   
 


