// This file was auto-generated by the veyron vdl tool.
var vom = require('vom');
// TODO(bjornick): Remove unused imports.
var Types = vom.Types;
var Type = vom.Type;
var Kind = vom.Kind;
var BigInt = vom.BigInt;
var Complex = vom.Complex;
var Builtins = vom.Builtins;
var Registry = vom.Registry;





module.exports = {};



// Types:
var _typeMessage = new Type();
var _typeRequest = new Type();
var _typeResponse = new Type();
_typeMessage.kind = Kind.ONEOF;
_typeMessage.name = "v.io/wspr/veyron/services/wsprd/channel.Message";
_typeMessage.fields = [{name: "Request", type: _typeRequest}, {name: "Response", type: _typeResponse}];
_typeRequest.kind = Kind.STRUCT;
_typeRequest.name = "v.io/wspr/veyron/services/wsprd/channel.Request";
_typeRequest.fields = [{name: "Type", type: Types.STRING}, {name: "Seq", type: Types.UINT32}, {name: "Body", type: Types.ANY}];
_typeResponse.kind = Kind.STRUCT;
_typeResponse.name = "v.io/wspr/veyron/services/wsprd/channel.Response";
_typeResponse.fields = [{name: "ReqSeq", type: Types.UINT32}, {name: "Err", type: Types.STRING}, {name: "Body", type: Types.ANY}];
module.exports.Message = (Registry.lookupOrCreateConstructor(_typeMessage));
module.exports.Request = (Registry.lookupOrCreateConstructor(_typeRequest));
module.exports.Response = (Registry.lookupOrCreateConstructor(_typeResponse));




// Consts:




function NotImplementedMethod(name) {
  throw new Error('Method ' + name + ' not implemented');
}


// Services:

   
 


