// This file was auto-generated by the veyron vdl tool.
var vom = require('../../../../../.././vom/vom');





module.exports = {};



// Types:
var _typeMessage = new vom.Type();
var _typeRequest = new vom.Type();
var _typeResponse = new vom.Type();
_typeMessage.kind = vom.Kind.UNION;
_typeMessage.name = "v.io/wspr/veyron/services/wsprd/channel.Message";
_typeMessage.fields = [{name: "Request", type: _typeRequest}, {name: "Response", type: _typeResponse}];
_typeRequest.kind = vom.Kind.STRUCT;
_typeRequest.name = "v.io/wspr/veyron/services/wsprd/channel.Request";
_typeRequest.fields = [{name: "Type", type: vom.Types.STRING}, {name: "Seq", type: vom.Types.UINT32}, {name: "Body", type: vom.Types.ANY}];
_typeResponse.kind = vom.Kind.STRUCT;
_typeResponse.name = "v.io/wspr/veyron/services/wsprd/channel.Response";
_typeResponse.fields = [{name: "ReqSeq", type: vom.Types.UINT32}, {name: "Err", type: vom.Types.STRING}, {name: "Body", type: vom.Types.ANY}];
module.exports.Message = (vom.Registry.lookupOrCreateConstructor(_typeMessage));
module.exports.Request = (vom.Registry.lookupOrCreateConstructor(_typeRequest));
module.exports.Response = (vom.Registry.lookupOrCreateConstructor(_typeResponse));




// Consts:



// Errors:



function NotImplementedMethod(name) {
  throw new Error('Method ' + name + ' not implemented');
}


// Services:

   
 


