// This file was auto-generated by the veyron vdl tool.
var vom = require('../../../.././vom/vom');
var makeError = require('../../../.././errors/make-errors');
var actions = require('../../../.././errors/actions');





var uniqueid = require('./../uniqueid/uniqueid');

module.exports = {};



// Types:
var _type1 = new vom.Type();
var _type2 = new vom.Type();
var _type3 = new vom.Type();
var _type4 = new vom.Type();
var _type5 = new vom.Type();
var _type6 = new vom.Type();
var _type7 = new vom.Type();
var _typeBlessingPattern = new vom.Type();
var _typeCaveat = new vom.Type();
var _typeCaveatDescriptor = new vom.Type();
var _typeCertificate = new vom.Type();
var _typeDischargeImpetus = new vom.Type();
var _typeHash = new vom.Type();
var _typeSignature = new vom.Type();
var _typeThirdPartyRequirements = new vom.Type();
var _typeWireBlessings = new vom.Type();
var _typemethodCaveat = new vom.Type();
var _typenonce = new vom.Type();
var _typepublicKeyDischarge = new vom.Type();
var _typepublicKeyThirdPartyCaveat = new vom.Type();
var _typeunixTimeExpiryCaveat = new vom.Type();
_type1.kind = vom.Kind.LIST;
_type1.name = "";
_type1.elem = _typeCaveat;
_type2.kind = vom.Kind.LIST;
_type2.name = "";
_type2.elem = vom.Types.BYTE;
_type3.kind = vom.Kind.LIST;
_type3.name = "";
_type3.elem = vom.Types.STRING;
_type4.kind = vom.Kind.LIST;
_type4.name = "";
_type4.elem = _typeBlessingPattern;
_type5.kind = vom.Kind.LIST;
_type5.name = "";
_type5.elem = vom.Types.ANY;
_type6.kind = vom.Kind.LIST;
_type6.name = "";
_type6.elem = _type7;
_type7.kind = vom.Kind.LIST;
_type7.name = "";
_type7.elem = _typeCertificate;
_typeBlessingPattern.kind = vom.Kind.STRING;
_typeBlessingPattern.name = "v.io/core/veyron2/security.BlessingPattern";
_typeCaveat.kind = vom.Kind.STRUCT;
_typeCaveat.name = "v.io/core/veyron2/security.Caveat";
_typeCaveat.fields = [{name: "ValidatorVOM", type: _type2}, {name: "Id", type: new uniqueid.Id()._type}, {name: "ParamVom", type: _type2}];
_typeCaveatDescriptor.kind = vom.Kind.STRUCT;
_typeCaveatDescriptor.name = "v.io/core/veyron2/security.CaveatDescriptor";
_typeCaveatDescriptor.fields = [{name: "Id", type: new uniqueid.Id()._type}, {name: "ParamType", type: vom.Types.TYPEOBJECT}];
_typeCertificate.kind = vom.Kind.STRUCT;
_typeCertificate.name = "v.io/core/veyron2/security.Certificate";
_typeCertificate.fields = [{name: "Extension", type: vom.Types.STRING}, {name: "PublicKey", type: _type2}, {name: "Caveats", type: _type1}, {name: "Signature", type: _typeSignature}];
_typeDischargeImpetus.kind = vom.Kind.STRUCT;
_typeDischargeImpetus.name = "v.io/core/veyron2/security.DischargeImpetus";
_typeDischargeImpetus.fields = [{name: "Server", type: _type4}, {name: "Method", type: vom.Types.STRING}, {name: "Arguments", type: _type5}];
_typeHash.kind = vom.Kind.STRING;
_typeHash.name = "v.io/core/veyron2/security.Hash";
_typeSignature.kind = vom.Kind.STRUCT;
_typeSignature.name = "v.io/core/veyron2/security.Signature";
_typeSignature.fields = [{name: "Purpose", type: _type2}, {name: "Hash", type: _typeHash}, {name: "R", type: _type2}, {name: "S", type: _type2}];
_typeThirdPartyRequirements.kind = vom.Kind.STRUCT;
_typeThirdPartyRequirements.name = "v.io/core/veyron2/security.ThirdPartyRequirements";
_typeThirdPartyRequirements.fields = [{name: "ReportServer", type: vom.Types.BOOL}, {name: "ReportMethod", type: vom.Types.BOOL}, {name: "ReportArguments", type: vom.Types.BOOL}];
_typeWireBlessings.kind = vom.Kind.STRUCT;
_typeWireBlessings.name = "v.io/core/veyron2/security.WireBlessings";
_typeWireBlessings.fields = [{name: "CertificateChains", type: _type6}];
_typemethodCaveat.kind = vom.Kind.LIST;
_typemethodCaveat.name = "v.io/core/veyron2/security.methodCaveat";
_typemethodCaveat.elem = vom.Types.STRING;
_typenonce.kind = vom.Kind.ARRAY;
_typenonce.name = "v.io/core/veyron2/security.nonce";
_typenonce.len = 16;
_typenonce.elem = vom.Types.BYTE;
_typepublicKeyDischarge.kind = vom.Kind.STRUCT;
_typepublicKeyDischarge.name = "v.io/core/veyron2/security.publicKeyDischarge";
_typepublicKeyDischarge.fields = [{name: "ThirdPartyCaveatID", type: vom.Types.STRING}, {name: "Caveats", type: _type1}, {name: "Signature", type: _typeSignature}];
_typepublicKeyThirdPartyCaveat.kind = vom.Kind.STRUCT;
_typepublicKeyThirdPartyCaveat.name = "v.io/core/veyron2/security.publicKeyThirdPartyCaveat";
_typepublicKeyThirdPartyCaveat.fields = [{name: "Nonce", type: _typenonce}, {name: "Caveats", type: _type1}, {name: "DischargerKey", type: _type2}, {name: "DischargerLocation", type: vom.Types.STRING}, {name: "DischargerRequirements", type: _typeThirdPartyRequirements}];
_typeunixTimeExpiryCaveat.kind = vom.Kind.INT64;
_typeunixTimeExpiryCaveat.name = "v.io/core/veyron2/security.unixTimeExpiryCaveat";
module.exports.BlessingPattern = (vom.Registry.lookupOrCreateConstructor(_typeBlessingPattern));
module.exports.Caveat = (vom.Registry.lookupOrCreateConstructor(_typeCaveat));
module.exports.CaveatDescriptor = (vom.Registry.lookupOrCreateConstructor(_typeCaveatDescriptor));
module.exports.Certificate = (vom.Registry.lookupOrCreateConstructor(_typeCertificate));
module.exports.DischargeImpetus = (vom.Registry.lookupOrCreateConstructor(_typeDischargeImpetus));
module.exports.Hash = (vom.Registry.lookupOrCreateConstructor(_typeHash));
module.exports.Signature = (vom.Registry.lookupOrCreateConstructor(_typeSignature));
module.exports.ThirdPartyRequirements = (vom.Registry.lookupOrCreateConstructor(_typeThirdPartyRequirements));
module.exports.WireBlessings = (vom.Registry.lookupOrCreateConstructor(_typeWireBlessings));
module.exports.methodCaveat = (vom.Registry.lookupOrCreateConstructor(_typemethodCaveat));
module.exports.nonce = (vom.Registry.lookupOrCreateConstructor(_typenonce));
module.exports.publicKeyDischarge = (vom.Registry.lookupOrCreateConstructor(_typepublicKeyDischarge));
module.exports.publicKeyThirdPartyCaveat = (vom.Registry.lookupOrCreateConstructor(_typepublicKeyThirdPartyCaveat));
module.exports.unixTimeExpiryCaveat = (vom.Registry.lookupOrCreateConstructor(_typeunixTimeExpiryCaveat));




// Consts:

  module.exports.UnixTimeExpiryCaveatX = new (vom.Registry.lookupOrCreateConstructor(_typeCaveatDescriptor))({
  'id': new Uint8Array([
84,
166,
118,
57,
129,
55,
24,
126,
205,
178,
109,
45,
105,
186,
0,
4,
]),
  'paramType': vom.Types.INT64,
});

  module.exports.MethodCaveatX = new (vom.Registry.lookupOrCreateConstructor(_typeCaveatDescriptor))({
  'id': new Uint8Array([
84,
166,
118,
57,
129,
55,
24,
126,
205,
178,
109,
45,
105,
186,
0,
3,
]),
  'paramType': _type3,
});

  module.exports.PublicKeyThirdPartyCaveatX = new (vom.Registry.lookupOrCreateConstructor(_typeCaveatDescriptor))({
  'id': new Uint8Array([
121,
114,
206,
23,
74,
123,
169,
63,
121,
84,
125,
118,
156,
145,
128,
0,
]),
  'paramType': _typepublicKeyThirdPartyCaveat,
});

  module.exports.NoExtension = new (vom.Registry.lookupOrCreateConstructor(_typeBlessingPattern))("$");

  module.exports.AllPrincipals = new (vom.Registry.lookupOrCreateConstructor(_typeBlessingPattern))("...");

  module.exports.ChainSeparator = new (vom.Registry.lookupOrCreateConstructor(vom.Types.STRING))("/");

  module.exports.SHA1Hash = new (vom.Registry.lookupOrCreateConstructor(_typeHash))("SHA1");

  module.exports.SHA256Hash = new (vom.Registry.lookupOrCreateConstructor(_typeHash))("SHA256");

  module.exports.SHA384Hash = new (vom.Registry.lookupOrCreateConstructor(_typeHash))("SHA384");

  module.exports.SHA512Hash = new (vom.Registry.lookupOrCreateConstructor(_typeHash))("SHA512");

  module.exports.SignatureForMessageSigning = new (vom.Registry.lookupOrCreateConstructor(vom.Types.STRING))("S");

  module.exports.SignatureForBlessingCertificates = new (vom.Registry.lookupOrCreateConstructor(vom.Types.STRING))("B");

  module.exports.SignatureForDischarge = new (vom.Registry.lookupOrCreateConstructor(vom.Types.STRING))("D");



// Errors:

module.exports.ErrCaveatNotRegistered = makeError('v.io/core/veyron2/security.ErrCaveatNotRegistered', actions.NO_RETRY, {
  'en': '{1:}{2:} no validation function registered for caveat id {3}',
}, [
  new uniqueid.Id()._type,
]);


module.exports.ErrCaveatParamTypeMismatch = makeError('v.io/core/veyron2/security.ErrCaveatParamTypeMismatch', actions.NO_RETRY, {
  'en': '{1:}{2:} bad param type: caveat {3} got {4}, want {5}',
}, [
  new uniqueid.Id()._type,
  vom.Types.TYPEOBJECT,
  vom.Types.STRING,
]);


module.exports.ErrCaveatParamCoding = makeError('v.io/core/veyron2/security.ErrCaveatParamCoding', actions.NO_RETRY, {
  'en': '{1:}{2:} unable to encode/decode caveat param(type={4}) for caveat {3}: {5}',
}, [
  new uniqueid.Id()._type,
  vom.Types.TYPEOBJECT,
  vom.Types.ANY,
]);


module.exports.ErrCaveatValidation = makeError('v.io/core/veyron2/security.ErrCaveatValidation', actions.NO_RETRY, {
  'en': '{1:}{2:} caveat validation failed: {3}',
}, [
  vom.Types.ANY,
]);




// Services:

   

   
 


