// This file was auto-generated by the veyron vdl tool.
var vdl = require('../../../../.././vdl');






module.exports = {};



// Types:
var _typeMyTime = new vdl.Type();
_typeMyTime.kind = vdl.Kind.INT32;
_typeMyTime.name = "v.io/v23/vdl/testdata/nativedep2.MyTime";
_typeMyTime.freeze();
module.exports.MyTime = (vdl.Registry.lookupOrCreateConstructor(_typeMyTime));




// Consts:



// Errors:



// Services:

   
 


