// Copyright 2015 The Vanadium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

/**
 * @fileoverview constants for security labels
 * TODO(bjornick): Remove when generated by vdl compiler.
 * @private
 */
module.exports = {
  RESOLVE: 1,
  READ: 2,
  WRITE: 4,
  ADMIN: 8,
  DEBUG: 16,
  MONITORING: 32,
};
