/**
 * @fileoverview constants for security labels
 * TODO(bjornick): Remove when generated by vdl compiler.
 * @private
 */
module.exports = {
  RESOLVE: 1,
  READ: 2,
  WRITE: 4,
  ADMIN: 8,
  DEBUG: 16,
  MONITORING: 32,
};
